import type { Metadata } from "next";
import "./globals.css";
import ClerkProvider from "@/providers/clerkProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function GlobalProviders ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      {children}
    </ClerkProvider>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={'antialiased'}
      >
        <GlobalProviders>
          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
